# This is the workflow that will build and push the Docker Image into a Docker Hub
name: Push to DockerHub
# Workflow is triggered manually (workflow dispatch)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: build dev image or prod image
        type: choice
        required: true
        options:
          - dev
          - prod

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Docker Token to .env File
        run: | 
            echo BOT_TOKEN=${{secrets.BOT_TOKEN}} >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          target: ${{ inputs.environment }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/japanese-language-bot-${{ inputs.environment }}:latest